-- ============================================================
-- MIGRATION : equipe_id (à exécuter UNE SEULE FOIS sur la base de production)
-- ============================================================
-- Changement du schéma pour que chantiers.equipe et conges.equipe
-- référencent equipes.id (stable) au lieu de l'index de tableau (fragile)
-- ============================================================

-- 1. Ajout de la colonne de flag aux companies
ALTER TABLE companies ADD COLUMN IF NOT EXISTS equipe_id_migrated BOOLEAN DEFAULT false;

-- 2. Passage de GENERATED ALWAYS à GENERATED BY DEFAULT pour permettre l'upsert
ALTER TABLE equipes ALTER COLUMN id DROP IDENTITY;
ALTER TABLE equipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Vérification
SELECT column_name, is_identity, identity_generation
FROM information_schema.columns
WHERE table_name = 'equipes' AND column_name = 'id';
-- Résultat attendu : is_identity = YES, identity_generation = BY DEFAULT
