-- ============================================================
-- SCHÉMA COMPLET - Planning Chantier
-- ============================================================

-- 1. COMPANIES
CREATE TABLE IF NOT EXISTS companies (
  id TEXT PRIMARY KEY,
  nom TEXT NOT NULL,
  secteur TEXT DEFAULT '',
  plan TEXT DEFAULT 'Starter',
  free INTEGER DEFAULT 1
);

INSERT INTO companies (id, nom, secteur, plan, free) VALUES
  ('batiouest', 'Bati Ouest', 'Charpente', 'Pro', 1)
ON CONFLICT (id) DO NOTHING;

-- 2. PROFILES (lie les auth.users Supabase aux données métier)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  nom TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'planning',
  must_change_password INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. USER_COMPANIES (liaison utilisateurs <-> entreprises)
CREATE TABLE IF NOT EXISTS user_companies (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, company_id)
);

-- 4. EQUIPES
CREATE TABLE IF NOT EXISTS equipes (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  ordre INTEGER NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '#7dd3fc',
  UNIQUE (company_id, nom)
);

-- 5. CHANTIERS
CREATE TABLE IF NOT EXISTS chantiers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  equipe INTEGER NOT NULL DEFAULT 0,
  start TEXT NOT NULL,
  duree INTEGER NOT NULL DEFAULT 1,
  nom TEXT NOT NULL,
  color TEXT DEFAULT '#b7c6d8',
  note TEXT DEFAULT '',
  termine INTEGER DEFAULT 0,
  linked INTEGER DEFAULT 0,
  detail TEXT DEFAULT '',
  force_aout INTEGER DEFAULT 0,
  permis INTEGER DEFAULT 0,
  financement INTEGER DEFAULT 0,
  danger INTEGER DEFAULT 0,
  reunion INTEGER DEFAULT 0,
  facture INTEGER DEFAULT 0,
  montant_devis INTEGER DEFAULT 0
);

-- 6. CONGES
CREATE TABLE IF NOT EXISTS conges (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  equipe INTEGER NOT NULL DEFAULT 0,
  start TEXT NOT NULL,
  duree INTEGER NOT NULL DEFAULT 1,
  nom TEXT DEFAULT 'Congé',
  all_equipes INTEGER DEFAULT 0
);

-- 7. CUSTOM_FERIES
CREATE TABLE IF NOT EXISTS custom_feries (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  date TEXT NOT NULL
);

-- ============================================================
-- MIGRATIONS (suppression conducteurs + ajout nouveaux champs)
-- ============================================================

-- Suppression des conducteurs (table entièrement retirée)
DROP TABLE IF EXISTS conducteurs;

-- Suppression de l'ancienne colonne conducteurId des chantiers
ALTER TABLE chantiers DROP COLUMN IF EXISTS "conducteurId";

-- Suppression des couleurs conducteurs sur companies
ALTER TABLE companies DROP COLUMN IF EXISTS conducteur_colors;

-- Ajout des nouvelles colonnes si non présentes (compatibilité)
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS permis INTEGER DEFAULT 0;
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS financement INTEGER DEFAULT 0;
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS danger INTEGER DEFAULT 0;
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS reunion INTEGER DEFAULT 0;
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS facture INTEGER DEFAULT 0;
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS montant_devis INTEGER DEFAULT 0;
ALTER TABLE equipes ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#7dd3fc';
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS force_aout INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS must_change_password INTEGER DEFAULT 0;
ALTER TABLE conges ADD COLUMN IF NOT EXISTS all_equipes INTEGER DEFAULT 0;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS chantier_colors TEXT[] DEFAULT ARRAY['#2563eb','#93c5fd','#eab308','#15803d','#6b7280','#f97316','#7dd3fc']::TEXT[];

-- ============================================================
-- SEED DATA - Chaque entreprise reçoit ses équipes
-- ============================================================

-- Équipes (16 par entreprise) : les 5 premières en bleu clair,
-- les suivantes en orange (sous-traitants)
DO $$
DECLARE
  comp RECORD;
  i INT;
BEGIN
  FOR comp IN SELECT id FROM companies LOOP
    FOR i IN 1..16 LOOP
      INSERT INTO equipes (company_id, nom, ordre, color)
      VALUES (comp.id, 'Équipe ' || i, i, CASE WHEN i <= 5 THEN '#7dd3fc' ELSE '#f97316' END)
      ON CONFLICT DO NOTHING;
    END LOOP;
  END LOOP;
END $$;

-- Chantiers (pour l'entreprise batiouest)
INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, color, note, termine, linked) VALUES
  (1, 'batiouest', 1, '2026-05-04', 10, 'Fermettes',               '#b7c6d8', 'Prévoir livraison matériel avant démarrage.', 0, 0),
  (2, 'batiouest', 1, '2026-05-18', 8,  'Charpente traditionnelle', '#c7f9c7', '', 0, 0),
  (3, 'batiouest', 2, '2026-05-04', 12, 'Toiture maison',           '#f9f9c7', '', 0, 0),
  (4, 'batiouest', 2, '2026-05-14', 15, 'Charpente hangar agricole', '#f9c7c7', '', 0, 0),
  (5, 'batiouest', 3, '2026-05-04', 7,  'Pose charpente bois',      '#c7e6f9', '', 0, 0),
  (6, 'batiouest', 3, '2026-05-20', 9,  'Couverture + charpente',   '#f0f0f0', '', 0, 0),
  (7, 'batiouest', 4, '2026-06-01', 6,  'Charpente extension',      '#b7c6d8', '', 0, 0),
  (8, 'batiouest', 4, '2026-06-03', 14, 'Ossature bois',            '#c7f9c7', '', 0, 0),
  (9, 'batiouest', 5, '2026-06-05', 4,  'Appentis',                 '#c7e6f9', '', 0, 0),
  (10, 'batiouest', 5, '2026-06-12', 5, 'Rénovation toiture',       '#f9c7c7', '', 1, 0)
ON CONFLICT (id) DO NOTHING;

-- Congés
INSERT INTO conges (id, company_id, equipe, start, duree, nom) VALUES
  (1, 'batiouest', 1, '2026-05-11', 3, 'Congé')
ON CONFLICT (id) DO NOTHING;

-- Activation RLS (sécurité multi-entreprises)
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE chantiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE conges ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_feries ENABLE ROW LEVEL SECURITY;

-- Politiques RLS : un utilisateur ne voit que ses entreprises
CREATE POLICY  "users can view own companies" ON companies
  FOR SELECT USING (
    id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own profile" ON profiles
  FOR SELECT USING (id = auth.uid());

-- RPC pour lister les utilisateurs (admin seulement, bypass RLS)
CREATE OR REPLACE FUNCTION get_users()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RETURN '[]'::JSONB;
  END IF;
  RETURN COALESCE((SELECT jsonb_agg(jsonb_build_object('id', id, 'email', email, 'nom', nom, 'role', role)) FROM profiles), '[]'::JSONB);
END;
$$;

CREATE POLICY  "users can view own company links" ON user_companies
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY  "users can view own company data" ON equipes
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON chantiers
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON conges
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON custom_feries
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

-- Politiques INSERT/UPDATE/DELETE pour les admins
CREATE POLICY  "admin insert" ON chantiers FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON chantiers FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON chantiers FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- Mêmes politiques pour conges
CREATE POLICY  "admin insert" ON conges FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON conges FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON conges FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- Pour equipes, custom_feries
CREATE POLICY  "admin insert" ON equipes FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON equipes FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON equipes FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

CREATE POLICY  "admin insert" ON custom_feries FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON custom_feries FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON custom_feries FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- ============================================================
-- RPC TRANSACTIONNELS (sauvegardes atomiques)
-- ============================================================

CREATE OR REPLACE FUNCTION replace_chantiers(p_company_id TEXT, p_chantiers JSONB)
RETURNS SETOF chantiers LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  -- Delete rows that exist in DB but NOT in the incoming array
  DELETE FROM chantiers
  WHERE company_id = p_company_id
  AND id NOT IN (
    SELECT (x->>'id')::INT FROM jsonb_array_elements(p_chantiers) AS x
    WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
  );
  -- Upsert all incoming rows (non-destructive)
  RETURN QUERY
  INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, color, note, termine, linked, detail, force_aout, permis, financement, danger, reunion, facture, montant_devis)
  SELECT COALESCE((x->>'id')::INT, nextval('chantiers_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT, (x->>'start')::TEXT, (x->>'duree')::INT,
         (x->>'nom')::TEXT, (x->>'color')::TEXT, (x->>'note')::TEXT,
         (x->>'termine')::INT, (x->>'linked')::INT, (x->>'detail')::TEXT, COALESCE((x->>'force_aout')::INT, 0),
         COALESCE((x->>'permis')::INT, 0), COALESCE((x->>'financement')::INT, 0),
         COALESCE((x->>'danger')::INT, 0), COALESCE((x->>'reunion')::INT, 0), COALESCE((x->>'facture')::INT, 0),
         COALESCE((x->>'montant_devis')::INT, 0)
  FROM jsonb_array_elements(p_chantiers) AS x
  ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    equipe = EXCLUDED.equipe,
    start = EXCLUDED.start,
    duree = EXCLUDED.duree,
    nom = EXCLUDED.nom,
    color = EXCLUDED.color,
    note = EXCLUDED.note,
    termine = EXCLUDED.termine,
    linked = EXCLUDED.linked,
    detail = EXCLUDED.detail,
    force_aout = EXCLUDED.force_aout,
    permis = EXCLUDED.permis,
    financement = EXCLUDED.financement,
    danger = EXCLUDED.danger,
    reunion = EXCLUDED.reunion,
    facture = EXCLUDED.facture,
    montant_devis = EXCLUDED.montant_devis
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_conges(p_company_id TEXT, p_conges JSONB)
RETURNS SETOF conges LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  -- Supprime les congés qui ne sont plus dans la liste entrante
  DELETE FROM conges
  WHERE company_id = p_company_id
  AND id NOT IN (
    SELECT (x->>'id')::INT FROM jsonb_array_elements(p_conges) AS x
    WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
  );
  RETURN QUERY
  INSERT INTO conges (id, company_id, equipe, start, duree, nom, all_equipes)
  SELECT COALESCE((x->>'id')::INT, nextval('conges_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT,
         (x->>'start')::TEXT, (x->>'duree')::INT, (x->>'nom')::TEXT,
         COALESCE((x->>'all_equipes')::INT, 0)
  FROM jsonb_array_elements(p_conges) AS x
  ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    equipe = EXCLUDED.equipe,
    start = EXCLUDED.start,
    duree = EXCLUDED.duree,
    nom = EXCLUDED.nom,
    all_equipes = EXCLUDED.all_equipes
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_equipes(p_company_id TEXT, p_equipes JSONB)
RETURNS SETOF equipes LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM equipes WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO equipes (company_id, nom, ordre, color)
  SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, COALESCE((x->>'ordre')::INT, 1), COALESCE((x->>'color'), '#7dd3fc')
  FROM jsonb_array_elements(p_equipes) AS x
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_custom_feries(p_company_id TEXT, p_feries JSONB)
RETURNS SETOF custom_feries LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM custom_feries WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO custom_feries (company_id, nom, date)
  SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'date')::TEXT
  FROM jsonb_array_elements(p_feries) AS x
  RETURNING *;
END;
$$;

-- RPC pour créer un utilisateur (admin seulement)
CREATE OR REPLACE FUNCTION create_user(p_email TEXT, p_password TEXT, p_nom TEXT, p_role TEXT, p_company_ids TEXT[])
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_user_id UUID;
  v_result JSONB;
  cid TEXT;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Seuls les admins peuvent créer des utilisateurs';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = p_email;

  IF v_user_id IS NULL THEN
    v_user_id := extensions.uuid_generate_v4();
    INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token, is_sso_user, is_anonymous)
    VALUES ('00000000-0000-0000-0000-000000000000', v_user_id, 'authenticated', 'authenticated', p_email, crypt(p_password, gen_salt('bf')), v_now, v_now, v_now, jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')), jsonb_build_object('role', p_role, 'nom', p_nom), v_now, v_now, '', '', '', '', false, false);
  ELSE
    UPDATE auth.users SET encrypted_password = crypt(p_password, gen_salt('bf')), updated_at = v_now, email_confirmed_at = v_now WHERE id = v_user_id;
  END IF;

  -- supprime puis recrée auth.identities (évite conflit de clé primaire)
  DELETE FROM auth.identities WHERE provider = 'email' AND provider_id = p_email;
  INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
  VALUES (
    v_user_id,
    v_user_id,
    jsonb_build_object('sub', v_user_id, 'email', p_email),
    'email',
    p_email,
    v_now,
    v_now,
    v_now
  );

  INSERT INTO profiles (id, email, nom, role, must_change_password)
  VALUES (v_user_id, p_email, p_nom, p_role, 1)
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, nom = EXCLUDED.nom, role = EXCLUDED.role;

  FOREACH cid IN ARRAY p_company_ids LOOP
    INSERT INTO user_companies (user_id, company_id) VALUES (v_user_id, cid) ON CONFLICT DO NOTHING;
  END LOOP;

  v_result := jsonb_build_object('id', v_user_id, 'email', p_email, 'nom', p_nom, 'role', p_role, 'must_change_password', 1, 'companyIds', to_jsonb(p_company_ids));
  RETURN v_result;
END;
$$;

-- RPC pour supprimer un utilisateur (admin seulement)
CREATE OR REPLACE FUNCTION delete_user(p_user_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Seuls les admins peuvent supprimer des utilisateurs';
  END IF;
  DELETE FROM auth.identities WHERE user_id = p_user_id;
  DELETE FROM user_companies WHERE user_id = p_user_id;
  DELETE FROM profiles WHERE id = p_user_id;
  DELETE FROM auth.users WHERE id = p_user_id;
END;
$$;

-- RPC pour changer le mot de passe (l'utilisateur lui-même, efface must_change_password)
CREATE OR REPLACE FUNCTION update_password(p_new_password TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE auth.users SET encrypted_password = crypt(p_new_password, gen_salt('bf')), updated_at = NOW() WHERE id = auth.uid();
  UPDATE profiles SET must_change_password = 0 WHERE id = auth.uid();
END;
$$;

-- RPC pour mettre à jour le profil d'un utilisateur (admin seulement)
CREATE OR REPLACE FUNCTION update_user_profile(p_user_id UUID, p_nom TEXT, p_role TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Accès refusé';
  END IF;
  UPDATE profiles SET nom = p_nom, role = p_role WHERE id = p_user_id;
END;
$$;

-- RPC pour mettre à jour les couleurs de toutes les entreprises
CREATE OR REPLACE FUNCTION update_all_colors(p_chantier_colors TEXT[])
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  UPDATE companies SET chantier_colors = p_chantier_colors;
END;
$$;

-- RPC pour charger toutes les données planning (bypass RLS pour l'affichage toutes entreprises)
CREATE OR REPLACE FUNCTION get_planning_data()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  result JSONB;
BEGIN
  SELECT jsonb_build_object(
    'companies', (
      SELECT jsonb_agg(jsonb_build_object('id', c.id, 'nom', c.nom, 'chantier_colors', COALESCE(c.chantier_colors, ARRAY['#2563eb','#93c5fd','#eab308','#15803d','#6b7280','#f97316','#7dd3fc']::TEXT[])))
      FROM (
        SELECT id, nom, chantier_colors FROM companies WHERE id = 'batiouest'
      ) c
    ),
    'equipes', (
      SELECT jsonb_agg(jsonb_build_object('nom', e.nom, 'company_id', e.company_id, 'ordre', e.ordre, 'color', COALESCE(e.color, '#7dd3fc')))
      FROM (
        SELECT nom, company_id, ordre, color
        FROM equipes
        ORDER BY
          CASE company_id
            WHEN 'batiouest' THEN 1
            ELSE 2
          END, ordre
      ) e
    ),
    'chantiers', (SELECT jsonb_agg(to_jsonb(ch)) FROM chantiers ch),
    'conges', (SELECT jsonb_agg(to_jsonb(co)) FROM conges co),
    'custom_feries', (SELECT jsonb_agg(to_jsonb(cf)) FROM custom_feries cf)
  ) INTO result;
  RETURN result;
END;
$$;

-- RPC batch : sauvegarde toutes les données en 1 appel
CREATE OR REPLACE FUNCTION save_all_planning_data(
  p_chantiers JSONB,
  p_conges JSONB,
  p_equipes JSONB,
  p_custom_feries JSONB,
  p_chantier_colors TEXT[]
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  comp_id TEXT;
  result JSONB;
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;

  FOR comp_id IN SELECT id FROM companies LOOP
    -- Chantiers
    DELETE FROM chantiers
    WHERE company_id = comp_id
    AND id NOT IN (
      SELECT (x->>'id')::INT FROM jsonb_array_elements(p_chantiers) AS x
      WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
      AND (x->>'company_id') = comp_id
    );
    INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, color, note, termine, linked, detail, force_aout, permis, financement, danger, reunion, facture, montant_devis)
    SELECT COALESCE((x->>'id')::INT, nextval('chantiers_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT, (x->>'start')::TEXT, (x->>'duree')::INT,
           (x->>'nom')::TEXT, (x->>'color')::TEXT, (x->>'note')::TEXT,
           (x->>'termine')::INT, (x->>'linked')::INT, (x->>'detail')::TEXT, COALESCE((x->>'force_aout')::INT, 0),
           COALESCE((x->>'permis')::INT, 0), COALESCE((x->>'financement')::INT, 0),
           COALESCE((x->>'danger')::INT, 0), COALESCE((x->>'reunion')::INT, 0), COALESCE((x->>'facture')::INT, 0),
           COALESCE((x->>'montant_devis')::INT, 0)
    FROM jsonb_array_elements(p_chantiers) AS x
    WHERE (x->>'company_id') = comp_id
    ON CONFLICT (id) DO UPDATE SET
      company_id = EXCLUDED.company_id, equipe = EXCLUDED.equipe, start = EXCLUDED.start,
      duree = EXCLUDED.duree, nom = EXCLUDED.nom, color = EXCLUDED.color, note = EXCLUDED.note,
      termine = EXCLUDED.termine, linked = EXCLUDED.linked, detail = EXCLUDED.detail,
      force_aout = EXCLUDED.force_aout, permis = EXCLUDED.permis, financement = EXCLUDED.financement,
      danger = EXCLUDED.danger, reunion = EXCLUDED.reunion, facture = EXCLUDED.facture, montant_devis = EXCLUDED.montant_devis;

    -- Conges
    DELETE FROM conges
    WHERE company_id = comp_id
    AND id NOT IN (
      SELECT (x->>'id')::INT FROM jsonb_array_elements(p_conges) AS x
      WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
      AND (x->>'company_id') = comp_id
    );
    INSERT INTO conges (id, company_id, equipe, start, duree, nom, all_equipes)
    SELECT COALESCE((x->>'id')::INT, nextval('conges_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT,
           (x->>'start')::TEXT, (x->>'duree')::INT, (x->>'nom')::TEXT, COALESCE((x->>'all_equipes')::INT, 0)
    FROM jsonb_array_elements(p_conges) AS x
    WHERE (x->>'company_id') = comp_id
    ON CONFLICT (id) DO UPDATE SET
      company_id = EXCLUDED.company_id, equipe = EXCLUDED.equipe, start = EXCLUDED.start,
      duree = EXCLUDED.duree, nom = EXCLUDED.nom, all_equipes = EXCLUDED.all_equipes;

    -- Equipes
    DELETE FROM equipes WHERE company_id = comp_id;
    INSERT INTO equipes (company_id, nom, ordre, color)
    SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, COALESCE((x->>'ordre')::INT, 1), COALESCE((x->>'color'), '#7dd3fc')
    FROM jsonb_array_elements(p_equipes) AS x
    WHERE (x->>'company_id') = comp_id;

    -- Custom feries
    DELETE FROM custom_feries WHERE company_id = comp_id;
    INSERT INTO custom_feries (company_id, nom, date)
    SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'date')::TEXT
    FROM jsonb_array_elements(p_custom_feries) AS x
    WHERE (x->>'company_id') = comp_id;

    -- Couleurs
    UPDATE companies SET chantier_colors = p_chantier_colors WHERE id = comp_id;
  END LOOP;

  SELECT jsonb_build_object(
    'chantiers', (SELECT jsonb_agg(to_jsonb(ch) ORDER BY ch.id) FROM chantiers ch),
    'conges', (SELECT jsonb_agg(to_jsonb(co) ORDER BY co.id) FROM conges co),
    'equipes', (SELECT jsonb_agg(jsonb_build_object('nom', e.nom, 'company_id', e.company_id, 'ordre', e.ordre, 'color', COALESCE(e.color, '#7dd3fc')) ORDER BY e.ordre) FROM equipes e),
    'custom_feries', (SELECT jsonb_agg(to_jsonb(cf) ORDER BY cf.id) FROM custom_feries cf)
  ) INTO result;
  RETURN result;
END;
$$;
