-- ============================================================
-- SCHÉMA COMPLET - Planning Chantier
-- ============================================================

-- 1. COMPANIES
CREATE TABLE IF NOT EXISTS companies (
  id TEXT PRIMARY KEY,
  nom TEXT NOT NULL,
  secteur TEXT DEFAULT '',
  plan TEXT DEFAULT 'Starter',
  free INTEGER DEFAULT 1
);

INSERT INTO companies (id, nom, secteur, plan, free) VALUES
  ('noree',   'Norée construction', 'BTP', 'Pro', 1),
  ('couvran', 'Couvran',            'BTP', 'Pro', 1),
  ('rat',     'Le Rat',             'BTP', 'Pro', 1)
ON CONFLICT (id) DO NOTHING;

-- 2. PROFILES (lie les auth.users Supabase aux données métier)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  nom TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'planning',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. USER_COMPANIES (liaison utilisateurs <-> entreprises)
CREATE TABLE IF NOT EXISTS user_companies (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, company_id)
);

-- 4. EQUIPES
CREATE TABLE IF NOT EXISTS equipes (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  ordre INTEGER NOT NULL DEFAULT 0,
  UNIQUE (company_id, nom)
);

-- 5. CONDUCTEURS
CREATE TABLE IF NOT EXISTS conducteurs (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#2563eb',
  UNIQUE (company_id, nom)
);

-- 6. CHANTIERS
CREATE TABLE IF NOT EXISTS chantiers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  equipe INTEGER NOT NULL DEFAULT 0,
  start TEXT NOT NULL,
  duree INTEGER NOT NULL DEFAULT 1,
  nom TEXT NOT NULL,
  "conducteurId" INTEGER DEFAULT 0,
  color TEXT DEFAULT '#b7c6d8',
  note TEXT DEFAULT '',
  termine INTEGER DEFAULT 0,
  linked INTEGER DEFAULT 0,
  detail TEXT DEFAULT '',
  force_aout INTEGER DEFAULT 0
);

-- 7. CONGES
CREATE TABLE IF NOT EXISTS conges (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  equipe INTEGER NOT NULL DEFAULT 0,
  start TEXT NOT NULL,
  duree INTEGER NOT NULL DEFAULT 1,
  nom TEXT DEFAULT 'Congé',
  all_equipes INTEGER DEFAULT 0
);

-- 8. CUSTOM_FERIES
CREATE TABLE IF NOT EXISTS custom_feries (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  date TEXT NOT NULL
);

-- ============================================================
-- SEED DATA - Chaque entreprise reçoit ses équipes/conducteurs
-- ============================================================

-- Équipes (16 par entreprise)
DO $$
DECLARE
  comp RECORD;
  i INT;
BEGIN
  FOR comp IN SELECT id FROM companies LOOP
    FOR i IN 1..16 LOOP
      INSERT INTO equipes (company_id, nom, ordre)
      VALUES (comp.id, 'Équipe ' || i, i)
      ON CONFLICT DO NOTHING;
    END LOOP;
  END LOOP;
END $$;

-- Conducteurs (3 par entreprise)
INSERT INTO conducteurs (company_id, nom, color) VALUES
  ('noree', 'Conducteur 1', '#2563eb'),
  ('noree', 'Conducteur 2', '#16a34a'),
  ('noree', 'Conducteur 3', '#dc2626'),
  ('couvran', 'Conducteur 1', '#2563eb'),
  ('couvran', 'Conducteur 2', '#16a34a'),
  ('couvran', 'Conducteur 3', '#dc2626'),
  ('rat', 'Conducteur 1', '#2563eb'),
  ('rat', 'Conducteur 2', '#16a34a'),
  ('rat', 'Conducteur 3', '#dc2626')
ON CONFLICT DO NOTHING;

-- Chantiers (pour l'entreprise noree)
INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, "conducteurId", color, note, termine, linked) VALUES
  (1, 'noree', 0, '2026-05-04', 10, 'Kervouch',          1, '#b7c6d8', 'Prévoir livraison matériel avant démarrage.', 0, 0),
  (2, 'noree', 0, '2026-05-18', 6,  'Cosperec énergie',  2, '#c7f9c7', '', 0, 0),
  (3, 'noree', 1, '2026-05-04', 8,  'Penhoat',           1, '#f9f9c7', '', 0, 0),
  (4, 'noree', 1, '2026-05-14', 5,  'Kerlouan',          3, '#f9c7c7', '', 0, 0),
  (5, 'noree', 2, '2026-05-04', 12, 'Roscoff',           2, '#c7e6f9', '', 0, 0),
  (6, 'noree', 2, '2026-05-20', 4,  'Plouescat',         1, '#f0f0f0', '', 0, 0),
  (7, 'noree', 0, '2026-06-01', 8,  'Pontivy',           1, '#b7c6d8', '', 0, 0),
  (8, 'noree', 1, '2026-06-03', 6,  'Lorient',           2, '#c7f9c7', '', 0, 0),
  (9, 'noree', 2, '2026-06-05', 10, 'Quimper',           3, '#f9c7c7', '', 0, 0),
  (10, 'noree', 1, '2026-06-12', 5,  'Brest',            1, '#c7e6f9', '', 0, 0)
ON CONFLICT (id) DO NOTHING;

-- Congés
INSERT INTO conges (id, company_id, equipe, start, duree, nom) VALUES
  (1, 'noree', 0, '2026-05-11', 3, 'Congé')
ON CONFLICT (id) DO NOTHING;

-- Activation RLS (sécurité multi-entreprises)
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE conducteurs ENABLE ROW LEVEL SECURITY;
ALTER TABLE chantiers ADD COLUMN IF NOT EXISTS force_aout INTEGER DEFAULT 0;
ALTER TABLE chantiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE conges ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_feries ENABLE ROW LEVEL SECURITY;

-- Politiques RLS : un utilisateur ne voit que ses entreprises
CREATE POLICY  "users can view own companies" ON companies
  FOR SELECT USING (
    id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own profile" ON profiles
  FOR SELECT USING (id = auth.uid());

-- RPC pour lister les utilisateurs (admin seulement, bypass RLS)
CREATE OR REPLACE FUNCTION get_users()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Accès refusé';
  END IF;
  RETURN (SELECT jsonb_agg(jsonb_build_object('id', id, 'email', email, 'nom', nom, 'role', role)) FROM profiles);
END;
$$;

CREATE POLICY  "users can view own company links" ON user_companies
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY  "users can view own company data" ON equipes
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON conducteurs
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON chantiers
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON conges
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY  "users can view own company data" ON custom_feries
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

-- Politiques INSERT/UPDATE/DELETE pour les admins
CREATE POLICY  "admin insert" ON chantiers FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON chantiers FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON chantiers FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- Mêmes politiques pour conges
CREATE POLICY  "admin insert" ON conges FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON conges FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON conges FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- Pour equipes, conducteurs, custom_feries
CREATE POLICY  "admin insert" ON equipes FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON equipes FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON equipes FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

CREATE POLICY  "admin insert" ON conducteurs FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON conducteurs FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON conducteurs FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

CREATE POLICY  "admin insert" ON custom_feries FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin update" ON custom_feries FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY  "admin delete" ON custom_feries FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- ============================================================
-- RPC TRANSACTIONNELS (sauvegardes atomiques)
-- ============================================================

-- RPC pour conducteurs : upsert par nom (préserve les IDs)
CREATE OR REPLACE FUNCTION upsert_conducteurs(p_company_id TEXT, p_conducteurs JSONB)
RETURNS SETOF conducteurs LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  r JSONB;
BEGIN
  FOR r IN SELECT * FROM jsonb_array_elements(p_conducteurs) LOOP
    INSERT INTO conducteurs (company_id, nom, color)
    VALUES (p_company_id, r->>'nom', r->>'color')
    ON CONFLICT (company_id, nom) DO UPDATE SET color = EXCLUDED.color;
  END LOOP;
  RETURN QUERY SELECT * FROM conducteurs WHERE company_id = p_company_id ORDER BY id;
END;
$$;

CREATE OR REPLACE FUNCTION replace_chantiers(p_company_id TEXT, p_chantiers JSONB)
RETURNS SETOF chantiers LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM chantiers WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, "conducteurId", color, note, termine, linked, detail, force_aout)
  SELECT COALESCE((x->>'id')::INT, nextval('chantiers_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT, (x->>'start')::TEXT, (x->>'duree')::INT,
         (x->>'nom')::TEXT, (x->>'conducteurId')::INT, (x->>'color')::TEXT, (x->>'note')::TEXT,
         (x->>'termine')::INT, (x->>'linked')::INT, (x->>'detail')::TEXT, COALESCE((x->>'force_aout')::BOOLEAN, false)
  FROM jsonb_array_elements(p_chantiers) AS x
  RETURNING *;
END;
$$;

ALTER TABLE conges ADD COLUMN IF NOT EXISTS all_equipes INTEGER DEFAULT 0;

CREATE OR REPLACE FUNCTION replace_conges(p_company_id TEXT, p_conges JSONB)
RETURNS SETOF conges LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM conges WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO conges (id, company_id, equipe, start, duree, nom, all_equipes)
  SELECT COALESCE((x->>'id')::INT, nextval('conges_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT,
         (x->>'start')::TEXT, (x->>'duree')::INT, (x->>'nom')::TEXT,
         COALESCE((x->>'all_equipes')::INT, 0)
  FROM jsonb_array_elements(p_conges) AS x
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_equipes(p_company_id TEXT, p_equipes JSONB)
RETURNS SETOF equipes LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM equipes WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO equipes (company_id, nom, ordre)
  SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'ordre')::INT
  FROM jsonb_array_elements(p_equipes) AS x
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_custom_feries(p_company_id TEXT, p_feries JSONB)
RETURNS SETOF custom_feries LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  DELETE FROM custom_feries WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO custom_feries (company_id, nom, date)
  SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'date')::TEXT
  FROM jsonb_array_elements(p_feries) AS x
  RETURNING *;
END;
$$;

-- Ajout colonnes couleurs pour companies (si pas déjà présentes)
ALTER TABLE companies ADD COLUMN IF NOT EXISTS chantier_colors TEXT[] DEFAULT ARRAY['#2563eb','#93c5fd','#eab308','#15803d','#6b7280','#f97316','#7dd3fc']::TEXT[];
ALTER TABLE companies ADD COLUMN IF NOT EXISTS conducteur_colors TEXT[] DEFAULT ARRAY['#2563eb','#16a34a','#dc2626','#9333ea','#ea580c','#0891b2','#ca8a04','#be123c']::TEXT[];

-- RPC pour créer un utilisateur (admin seulement)
CREATE OR REPLACE FUNCTION create_user(p_email TEXT, p_password TEXT, p_nom TEXT, p_role TEXT, p_company_ids TEXT[])
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_user_id UUID;
  v_result JSONB;
  cid TEXT;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Seuls les admins peuvent créer des utilisateurs';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = p_email;

  IF v_user_id IS NULL THEN
    v_user_id := extensions.uuid_generate_v4();
    INSERT INTO auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_sent_at, is_sso_user, is_anonymous)
    VALUES (
      v_user_id,
      '00000000-0000-0000-0000-000000000000',
      'authenticated',
      'authenticated',
      p_email,
      crypt(p_password, gen_salt('bf')),
      v_now,
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('role', p_role, 'nom', p_nom),
      v_now,
      v_now,
      v_now,
      false,
      false
    );
  ELSE
    -- mettre à jour le mot de passe si l'utilisateur existe déjà
    UPDATE auth.users SET encrypted_password = crypt(p_password, gen_salt('bf')), updated_at = v_now, email_confirmed_at = v_now WHERE id = v_user_id;
  END IF;

  -- créer auth.identities si manquant (indispensable pour la connexion)
  IF NOT EXISTS (SELECT 1 FROM auth.identities WHERE user_id = v_user_id AND provider = 'email') THEN
    INSERT INTO auth.identities (id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    VALUES (
      v_user_id,
      v_user_id,
      jsonb_build_object('sub', v_user_id, 'email', p_email),
      'email',
      v_now,
      v_now,
      v_now
    );
  END IF;

  INSERT INTO profiles (id, email, nom, role)
  VALUES (v_user_id, p_email, p_nom, p_role)
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, nom = EXCLUDED.nom, role = EXCLUDED.role;

  FOREACH cid IN ARRAY p_company_ids LOOP
    INSERT INTO user_companies (user_id, company_id) VALUES (v_user_id, cid) ON CONFLICT DO NOTHING;
  END LOOP;

  v_result := jsonb_build_object('id', v_user_id, 'email', p_email, 'nom', p_nom, 'role', p_role, 'companyIds', to_jsonb(p_company_ids));
  RETURN v_result;
END;
$$;

-- RPC pour supprimer un utilisateur (admin seulement)
CREATE OR REPLACE FUNCTION delete_user(p_user_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Seuls les admins peuvent supprimer des utilisateurs';
  END IF;
  DELETE FROM user_companies WHERE user_id = p_user_id;
  DELETE FROM profiles WHERE id = p_user_id;
  DELETE FROM auth.users WHERE id = p_user_id;
END;
$$;

-- RPC pour mettre à jour les couleurs (bypass RLS)
CREATE OR REPLACE FUNCTION update_company_colors(p_company_id TEXT, p_chantier_colors TEXT[], p_conducteur_colors TEXT[])
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE companies
  SET chantier_colors = p_chantier_colors, conducteur_colors = p_conducteur_colors
  WHERE id = p_company_id;
END;
$$;

-- RPC pour charger toutes les données planning (bypass RLS pour l'affichage toutes entreprises)
CREATE OR REPLACE FUNCTION get_planning_data()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  result JSONB;
BEGIN
  SELECT jsonb_build_object(
    'companies', (
      SELECT jsonb_agg(jsonb_build_object('id', c.id, 'nom', c.nom, 'chantier_colors', COALESCE(c.chantier_colors, ARRAY['#2563eb','#93c5fd','#eab308','#15803d','#6b7280','#f97316','#7dd3fc']::TEXT[]), 'conducteur_colors', COALESCE(c.conducteur_colors, ARRAY['#2563eb','#16a34a','#dc2626','#9333ea','#ea580c','#0891b2','#ca8a04','#be123c']::TEXT[])))
      FROM (
        SELECT id, nom, chantier_colors, conducteur_colors FROM companies WHERE id = 'noree'
        UNION ALL
        SELECT id, nom, chantier_colors, conducteur_colors FROM companies WHERE id = 'couvran'
        UNION ALL
        SELECT id, nom, chantier_colors, conducteur_colors FROM companies WHERE id = 'rat'
      ) c
    ),
    'equipes', (
      SELECT jsonb_agg(jsonb_build_object('nom', e.nom, 'company_id', e.company_id, 'ordre', e.ordre))
      FROM (
        SELECT nom, company_id, ordre
        FROM equipes
        ORDER BY
          CASE company_id
            WHEN 'noree' THEN 1
            WHEN 'couvran' THEN 2
            WHEN 'rat' THEN 3
            ELSE 4
          END, ordre
      ) e
    ),
    'chantiers', (SELECT jsonb_agg(to_jsonb(ch)) FROM chantiers ch),
    'conges', (SELECT jsonb_agg(to_jsonb(co)) FROM conges co),
    'conducteurs', (SELECT jsonb_agg(to_jsonb(cd)) FROM conducteurs cd),
    'custom_feries', (SELECT jsonb_agg(to_jsonb(cf)) FROM custom_feries cf)
  ) INTO result;
  RETURN result;
END;
$$;
