-- ============================================================
-- SCHÉMA COMPLET - Planning Chantier (structure uniquement)
-- ============================================================
-- Ce fichier contient la structure de la base de données Supabase
-- sans les données de démonstration. Exécuter dans l'éditeur SQL
-- du dashboard Supabase pour recréer la base from scratch.

-- ============================================================
-- 1. TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS companies (
  id TEXT PRIMARY KEY,
  nom TEXT NOT NULL,
  secteur TEXT DEFAULT '',
  plan TEXT DEFAULT 'Starter',
  free INTEGER DEFAULT 1,
  chantier_colors TEXT[] DEFAULT ARRAY['#2563eb','#93c5fd','#eab308','#15803d','#6b7280','#f97316','#7dd3fc']::TEXT[],
  conducteur_colors TEXT[] DEFAULT ARRAY['#2563eb','#16a34a','#dc2626','#9333ea','#ea580c','#0891b2','#ca8a04','#be123c']::TEXT[],
  equipe_id_migrated BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  nom TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'planning',
  must_change_password INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_companies (
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, company_id)
);

CREATE TABLE IF NOT EXISTS equipes (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  ordre INTEGER NOT NULL DEFAULT 0,
  UNIQUE (company_id, nom)
);

CREATE TABLE IF NOT EXISTS conducteurs (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  nom TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#2563eb'
);

CREATE TABLE IF NOT EXISTS chantiers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  equipe INTEGER NOT NULL DEFAULT 0,
  start TEXT NOT NULL,
  duree INTEGER NOT NULL DEFAULT 1,
  nom TEXT NOT NULL,
  "conducteurId" INTEGER DEFAULT 0,
  color TEXT DEFAULT '#b7c6d8',
  note TEXT DEFAULT '',
  termine INTEGER DEFAULT 0,
  linked INTEGER DEFAULT 0,
  detail TEXT DEFAULT '',
  force_aout INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS conges (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  equipe INTEGER NOT NULL DEFAULT 0,
  start TEXT NOT NULL,
  duree INTEGER NOT NULL DEFAULT 1,
  nom TEXT DEFAULT 'Congé',
  all_equipes INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS custom_feries (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  nom TEXT NOT NULL,
  date TEXT NOT NULL
);

-- ============================================================
-- 2. ROW LEVEL SECURITY (RLS)
-- ============================================================

ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE conducteurs ENABLE ROW LEVEL SECURITY;
ALTER TABLE chantiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE conges ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_feries ENABLE ROW LEVEL SECURITY;

-- --- Politiques SELECT ---

CREATE POLICY "users can view own companies" ON companies
  FOR SELECT USING (
    id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "users can view own profile" ON profiles
  FOR SELECT USING (id = auth.uid());

CREATE POLICY "users can view own company links" ON user_companies
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "users can view own company data" ON equipes
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "users can view all conducteurs" ON conducteurs
  FOR SELECT USING (true);

CREATE POLICY "users can view own company data" ON chantiers
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "users can view own company data" ON conges
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

CREATE POLICY "users can view own company data" ON custom_feries
  FOR SELECT USING (
    company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
  );

-- --- Politiques INSERT/UPDATE/DELETE ---

CREATE POLICY "admin insert" ON chantiers FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin update" ON chantiers FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin delete" ON chantiers FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

CREATE POLICY "admin insert" ON conges FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin update" ON conges FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin delete" ON conges FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

CREATE POLICY "admin insert" ON equipes FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin update" ON equipes FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin delete" ON equipes FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

CREATE POLICY "admin insert" ON conducteurs FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'planning'))
);
CREATE POLICY "admin update" ON conducteurs FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'planning'))
);
CREATE POLICY "admin delete" ON conducteurs FOR DELETE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'planning'))
);

CREATE POLICY "admin insert" ON custom_feries FOR INSERT WITH CHECK (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin update" ON custom_feries FOR UPDATE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);
CREATE POLICY "admin delete" ON custom_feries FOR DELETE USING (
  company_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
);

-- ============================================================
-- 3. RPC / FONCTIONS STOCKÉES
-- ============================================================

-- Chargement de toutes les données planning (bypass RLS)
CREATE OR REPLACE FUNCTION get_planning_data()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  result JSONB;
BEGIN
  SELECT jsonb_build_object(
    'companies', (
      SELECT jsonb_agg(jsonb_build_object('id', c.id, 'nom', c.nom, 'chantier_colors', COALESCE(c.chantier_colors, ARRAY['#2563eb','#93c5fd','#eab308','#15803d','#6b7280','#f97316','#7dd3fc']::TEXT[]), 'conducteur_colors', COALESCE(c.conducteur_colors, ARRAY['#2563eb','#16a34a','#dc2626','#9333ea','#ea580c','#0891b2','#ca8a04','#be123c']::TEXT[])))
      FROM companies c
      ORDER BY c.id
    ),
    'equipes', (
      SELECT jsonb_agg(jsonb_build_object('id', e.id, 'nom', e.nom, 'company_id', e.company_id, 'ordre', e.ordre))
      FROM equipes e
      ORDER BY e.company_id, e.ordre
    ),
    'chantiers', (SELECT jsonb_agg(to_jsonb(ch)) FROM chantiers ch),
    'conges', (SELECT jsonb_agg(to_jsonb(co)) FROM conges co),
    'conducteurs', (SELECT jsonb_agg(jsonb_build_object('id', cd.id, 'nom', cd.nom, 'color', cd.color)) FROM conducteurs cd),
    'custom_feries', (SELECT jsonb_agg(to_jsonb(cf)) FROM custom_feries cf)
  ) INTO result;
  RETURN result;
END;
$$;

-- Sauvegarde atomique complète
CREATE OR REPLACE FUNCTION save_all_planning_data(
  p_chantiers JSONB,
  p_conges JSONB,
  p_equipes JSONB,
  p_conducteurs JSONB,
  p_custom_feries JSONB,
  p_chantier_colors TEXT[],
  p_conducteur_colors TEXT[]
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  comp_id TEXT;
  result JSONB;
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;

  FOR comp_id IN SELECT id FROM companies LOOP
    -- Chantiers
    DELETE FROM chantiers
    WHERE company_id = comp_id
    AND id NOT IN (
      SELECT (x->>'id')::INT FROM jsonb_array_elements(p_chantiers) AS x
      WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
      AND (x->>'company_id') = comp_id
    );
    INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, "conducteurId", color, note, termine, linked, detail, force_aout)
    SELECT COALESCE((x->>'id')::INT, nextval('chantiers_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT, (x->>'start')::TEXT, (x->>'duree')::INT,
           (x->>'nom')::TEXT, (x->>'conducteurId')::INT, (x->>'color')::TEXT, (x->>'note')::TEXT,
           (x->>'termine')::INT, (x->>'linked')::INT, (x->>'detail')::TEXT, COALESCE((x->>'force_aout')::INT, 0)::BOOLEAN
    FROM jsonb_array_elements(p_chantiers) AS x
    WHERE (x->>'company_id') = comp_id
    ON CONFLICT (id) DO UPDATE SET
      company_id = EXCLUDED.company_id, equipe = EXCLUDED.equipe, start = EXCLUDED.start,
      duree = EXCLUDED.duree, nom = EXCLUDED.nom, "conducteurId" = EXCLUDED."conducteurId",
      color = EXCLUDED.color, note = EXCLUDED.note, termine = EXCLUDED.termine,
      linked = EXCLUDED.linked, detail = EXCLUDED.detail, force_aout = EXCLUDED.force_aout;

    -- Congés
    DELETE FROM conges
    WHERE company_id = comp_id
    AND id NOT IN (
      SELECT (x->>'id')::INT FROM jsonb_array_elements(p_conges) AS x
      WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
      AND (x->>'company_id') = comp_id
    );
    INSERT INTO conges (id, company_id, equipe, start, duree, nom, all_equipes)
    SELECT COALESCE((x->>'id')::INT, nextval('conges_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT,
           (x->>'start')::TEXT, (x->>'duree')::INT, (x->>'nom')::TEXT, COALESCE((x->>'all_equipes')::INT, 0)
    FROM jsonb_array_elements(p_conges) AS x
    WHERE (x->>'company_id') = comp_id
    ON CONFLICT (id) DO UPDATE SET
      company_id = EXCLUDED.company_id, equipe = EXCLUDED.equipe, start = EXCLUDED.start,
      duree = EXCLUDED.duree, nom = EXCLUDED.nom, all_equipes = EXCLUDED.all_equipes;

    -- Équipes
    DELETE FROM equipes WHERE company_id = comp_id;
    INSERT INTO equipes (company_id, nom, ordre)
    SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, COALESCE((x->>'ordre')::INT, 1)
    FROM jsonb_array_elements(p_equipes) AS x
    WHERE (x->>'company_id') = comp_id;

    -- Custom feries
    DELETE FROM custom_feries WHERE company_id = comp_id;
    INSERT INTO custom_feries (company_id, nom, date)
    SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'date')::TEXT
    FROM jsonb_array_elements(p_custom_feries) AS x
    WHERE (x->>'company_id') = comp_id;

    -- Couleurs
    UPDATE companies
    SET chantier_colors = p_chantier_colors, conducteur_colors = p_conducteur_colors
    WHERE id = comp_id;
  END LOOP;

  -- Conducteurs (globaux)
  DELETE FROM conducteurs
  WHERE id NOT IN (
    SELECT (x->>'id')::INT FROM jsonb_array_elements(p_conducteurs) AS x
    WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
  );
  INSERT INTO conducteurs (nom, color)
  SELECT r->>'nom', r->>'color'
  FROM jsonb_array_elements(p_conducteurs) AS r
  ON CONFLICT (nom) DO UPDATE SET color = EXCLUDED.color;

  SELECT jsonb_build_object(
    'chantiers', (SELECT jsonb_agg(to_jsonb(ch) ORDER BY ch.id) FROM chantiers ch),
    'conges', (SELECT jsonb_agg(to_jsonb(co) ORDER BY co.id) FROM conges co),
    'equipes', (SELECT jsonb_agg(jsonb_build_object('nom', e.nom, 'company_id', e.company_id, 'ordre', e.ordre) ORDER BY e.ordre) FROM equipes e),
    'conducteurs', (SELECT jsonb_agg(jsonb_build_object('id', cd.id, 'nom', cd.nom, 'color', cd.color) ORDER BY cd.id) FROM conducteurs cd),
    'custom_feries', (SELECT jsonb_agg(to_jsonb(cf) ORDER BY cf.id) FROM custom_feries cf)
  ) INTO result;
  RETURN result;
END;
$$;

-- CRUD par entreprise
CREATE OR REPLACE FUNCTION replace_chantiers(p_company_id TEXT, p_chantiers JSONB)
RETURNS SETOF chantiers LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM chantiers WHERE company_id = p_company_id
  AND id NOT IN (
    SELECT (x->>'id')::INT FROM jsonb_array_elements(p_chantiers) AS x
    WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
  );
  RETURN QUERY
  INSERT INTO chantiers (id, company_id, equipe, start, duree, nom, "conducteurId", color, note, termine, linked, detail, force_aout)
  SELECT COALESCE((x->>'id')::INT, nextval('chantiers_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT, (x->>'start')::TEXT, (x->>'duree')::INT,
         (x->>'nom')::TEXT, (x->>'conducteurId')::INT, (x->>'color')::TEXT, (x->>'note')::TEXT,
         (x->>'termine')::INT, (x->>'linked')::INT, (x->>'detail')::TEXT, COALESCE((x->>'force_aout')::INT, 0)::BOOLEAN
  FROM jsonb_array_elements(p_chantiers) AS x
  ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id, equipe = EXCLUDED.equipe, start = EXCLUDED.start,
    duree = EXCLUDED.duree, nom = EXCLUDED.nom, "conducteurId" = EXCLUDED."conducteurId",
    color = EXCLUDED.color, note = EXCLUDED.note, termine = EXCLUDED.termine,
    linked = EXCLUDED.linked, detail = EXCLUDED.detail, force_aout = EXCLUDED.force_aout
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_conges(p_company_id TEXT, p_conges JSONB)
RETURNS SETOF conges LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM conges WHERE company_id = p_company_id
  AND id NOT IN (
    SELECT (x->>'id')::INT FROM jsonb_array_elements(p_conges) AS x
    WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
  );
  RETURN QUERY
  INSERT INTO conges (id, company_id, equipe, start, duree, nom, all_equipes)
  SELECT COALESCE((x->>'id')::INT, nextval('conges_id_seq'::regclass)), (x->>'company_id')::TEXT, (x->>'equipe')::INT,
         (x->>'start')::TEXT, (x->>'duree')::INT, (x->>'nom')::TEXT,
         COALESCE((x->>'all_equipes')::INT, 0)
  FROM jsonb_array_elements(p_conges) AS x
  ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id, equipe = EXCLUDED.equipe, start = EXCLUDED.start,
    duree = EXCLUDED.duree, nom = EXCLUDED.nom, all_equipes = EXCLUDED.all_equipes
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_equipes(p_company_id TEXT, p_equipes JSONB)
RETURNS SETOF equipes LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM equipes WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO equipes (company_id, nom, ordre)
  SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'ordre')::INT
  FROM jsonb_array_elements(p_equipes) AS x
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION replace_custom_feries(p_company_id TEXT, p_feries JSONB)
RETURNS SETOF custom_feries LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM custom_feries WHERE company_id = p_company_id;
  RETURN QUERY
  INSERT INTO custom_feries (company_id, nom, date)
  SELECT (x->>'company_id')::TEXT, (x->>'nom')::TEXT, (x->>'date')::TEXT
  FROM jsonb_array_elements(p_feries) AS x
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION upsert_conducteurs(p_conducteurs JSONB)
RETURNS SETOF conducteurs LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  r JSONB;
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  DELETE FROM conducteurs
  WHERE id NOT IN (
    SELECT (x->>'id')::INT FROM jsonb_array_elements(p_conducteurs) AS x
    WHERE (x->>'id') IS NOT NULL AND (x->>'id') ~ '^-?[0-9]+$'
  );
  FOR r IN SELECT * FROM jsonb_array_elements(p_conducteurs) LOOP
    INSERT INTO conducteurs (nom, color)
    VALUES (r->>'nom', r->>'color')
    ON CONFLICT (nom) DO UPDATE SET color = EXCLUDED.color;
  END LOOP;
  RETURN QUERY SELECT * FROM conducteurs ORDER BY id;
END;
$$;

-- Couleurs
CREATE OR REPLACE FUNCTION update_all_colors(p_chantier_colors TEXT[], p_conducteur_colors TEXT[])
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'lecture') THEN
    RAISE EXCEPTION 'Accès refusé : rôle lecture';
  END IF;
  UPDATE companies SET chantier_colors = p_chantier_colors, conducteur_colors = p_conducteur_colors;
END;
$$;

-- Gestion utilisateurs
CREATE OR REPLACE FUNCTION get_users()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RETURN '[]'::JSONB;
  END IF;
  RETURN COALESCE((SELECT jsonb_agg(jsonb_build_object('id', id, 'email', email, 'nom', nom, 'role', role)) FROM profiles), '[]'::JSONB);
END;
$$;

CREATE OR REPLACE FUNCTION create_user(p_email TEXT, p_password TEXT, p_nom TEXT, p_role TEXT, p_company_ids TEXT[])
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_user_id UUID;
  v_result JSONB;
  cid TEXT;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Seuls les admins peuvent créer des utilisateurs';
  END IF;

  SELECT id INTO v_user_id FROM auth.users WHERE email = p_email;

  IF v_user_id IS NULL THEN
    v_user_id := extensions.uuid_generate_v4();
    INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, recovery_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token, is_sso_user, is_anonymous)
    VALUES ('00000000-0000-0000-0000-000000000000', v_user_id, 'authenticated', 'authenticated', p_email, crypt(p_password, gen_salt('bf')), v_now, v_now, v_now, jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')), jsonb_build_object('role', p_role, 'nom', p_nom), v_now, v_now, '', '', '', '', false, false);
  ELSE
    UPDATE auth.users SET encrypted_password = crypt(p_password, gen_salt('bf')), updated_at = v_now, email_confirmed_at = v_now WHERE id = v_user_id;
  END IF;

  DELETE FROM auth.identities WHERE provider = 'email' AND provider_id = p_email;
  INSERT INTO auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
  VALUES (
    v_user_id, v_user_id,
    jsonb_build_object('sub', v_user_id, 'email', p_email),
    'email', p_email, v_now, v_now, v_now
  );

  INSERT INTO profiles (id, email, nom, role, must_change_password)
  VALUES (v_user_id, p_email, p_nom, p_role, 1)
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, nom = EXCLUDED.nom, role = EXCLUDED.role;

  FOREACH cid IN ARRAY p_company_ids LOOP
    INSERT INTO user_companies (user_id, company_id) VALUES (v_user_id, cid) ON CONFLICT DO NOTHING;
  END LOOP;

  v_result := jsonb_build_object('id', v_user_id, 'email', p_email, 'nom', p_nom, 'role', p_role, 'must_change_password', 1, 'companyIds', to_jsonb(p_company_ids));
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION delete_user(p_user_id UUID)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Seuls les admins peuvent supprimer des utilisateurs';
  END IF;
  DELETE FROM auth.identities WHERE user_id = p_user_id;
  DELETE FROM user_companies WHERE user_id = p_user_id;
  DELETE FROM profiles WHERE id = p_user_id;
  DELETE FROM auth.users WHERE id = p_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION update_password(p_new_password TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE auth.users SET encrypted_password = crypt(p_new_password, gen_salt('bf')), updated_at = NOW() WHERE id = auth.uid();
  UPDATE profiles SET must_change_password = 0 WHERE id = auth.uid();
END;
$$;

CREATE OR REPLACE FUNCTION update_user_profile(p_user_id UUID, p_nom TEXT, p_role TEXT)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') THEN
    RAISE EXCEPTION 'Accès refusé';
  END IF;
  UPDATE profiles SET nom = p_nom, role = p_role WHERE id = p_user_id;
END;
$$;

-- Migration
CREATE OR REPLACE FUNCTION mark_equipes_migrated(p_company_ids TEXT[])
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  cid TEXT;
BEGIN
  FOREACH cid IN ARRAY p_company_ids LOOP
    UPDATE companies SET equipe_id_migrated = true WHERE id = cid;
  END LOOP;
END;
$$;
